[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# PEP 420 namespace packages need some special treatment, see
# Thanks @jherland for the hints!
# https://realpython.com/python-namespace-package/
# https://peps.python.org/pep-0420/
[tool.setuptools.packages.find]
where = ["."]
include = ["freezing*"]
namespaces = true

[project]
name = "freezing-web"
version = "1.7.0"
description = "Freezing Saddles website component."
authors = [
    {name = "Hans Lellelid", email = "hans@xmpl.org"},
    {name = "Ian Will"},
    {name = "Jon Renaut"},
    {name = "Merlin Hughes"},
    {name = "Richard Bullington-McGuire", email = "richard.bullington.mcguire@gmail.com"},
    {name = "Adrian Porter"},
    {name = "Joe Tatsuko"}
]
license = {text = "Apache License (2.0)"}
requires-python = ">=3.14"
dependencies = [
    "Flask>=3.1.3,<4",
    "PyMySQL[rsa]>=1.1.2,<2",
    "PyYAML>=6.0.3,<7",
    "SQLAlchemy>=2.0.52,<3",
    # Thanks https://stackoverflow.com/a/77214086/424301 - Flask did not pin Werkzeug dep
    "Werkzeug>=3.1.8,<4",
    "colorlog>=6.10.1,<7",
    "python-dateutil>=2.9.0.post0,<3",
    "envparse>=0.2.0,<1",
    "freezing-common",
    "freezing-model",
    "marshmallow>=4.3.1,<5",
    "stravalib>=2.4,<3",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Games",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.14",
    "Natural Language :: English",
]

[project.optional-dependencies]
runtime = [
    "gunicorn>=26.2.0,<27",
]

[project.scripts]
freezing-server = "freezing.web.runserver:main"

[tool.fawltydeps]
ignore_unused = [
    "PyMySQL",
    "autoflake",
    "bandit",
    "black",
    "djlint",
    "fawltydeps",
    "flake8",
    "flake8-pyproject",
    "freezing-common",
    "freezing-common",
    "freezing-model",
    "gunicorn",
    "isort",
    "pre-commit",
    "pymarkdownlnt",
]

[tool.uv.sources]
freezing-common = { workspace = true }
freezing-model = { workspace = true }

# djlint looks for its config next to the templates, not at the workspace root
[tool.djlint]
line_break_after_multiline_tag=true
max_line_length=88
