---
name: Build

on: pull_request

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        app: [web, sync, nq, freezebot]
    uses: ./.github/workflows/build-docker.yml
    with:
      app: ${{ matrix.app }}
      tag: latest-actions-build
      push: false
