---
name: Teams

on:
  push:
    branches:
      - 'main'
    paths:
      - 'teams/**'
      - '.github/workflows/teams.yml'
  pull_request:
    paths:
      - 'teams/**'
      - '.github/workflows/teams.yml'

permissions:
  contents: read

jobs:
  build:
    name: teams
    permissions:
      checks: write        # for test results
      pull-requests: write # for test results
      contents: write      # for sbt-dependency-submission
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: temurin
          java-version: 25
          cache: sbt
      - uses: sbt/setup-sbt@82da71df4e122282484a99a8d70096bc2369dbd8 # v1.5.9
      - name: Run tests
        working-directory: teams
        run: sbt --server --batch test
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always()
        with:
          files: |
            teams/target/out/**/test-reports/*.xml
      - name: Upload dependency graph
        uses: scalacenter/sbt-dependency-submission@7b2f7e1418cb4a77fee99f9eb07c3f7577b9a867 # v3
        with:
          working-directory: teams
